# Pre-commit hooks configuration
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General file checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-added-large-files
    args: [--maxkb=1000]
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: check-ast
  - id: debug-statements
  - id: name-tests-test
    args: [--pytest-test-first]

  # Python code formatting with Black
- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
  - id: black
    language_version: python3
    args: [--line-length=100]

  # Import sorting with isort
- repo: https://github.com/PyCQA/isort
  rev: 7.0.0
  hooks:
  - id: isort
    args: [--profile=black, --line-length=100]

  # Linting with flake8
- repo: https://github.com/PyCQA/flake8
  rev: 7.3.0
  hooks:
  - id: flake8
    args: [--max-line-length=100, '--ignore=E203,E266,E501,W503,F403,F401', --max-complexity=18, '--select=B,C,E,F,W,T4,B9']
    additional_dependencies: [flake8-bugbear, flake8-comprehensions, flake8-simplify]

  # Type checking with mypy
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.18.2
  hooks:
  - id: mypy
    args: [--ignore-missing-imports, --no-strict-optional]
    additional_dependencies: [types-requests, types-redis]

  # Security linting with bandit
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    args: [-c, pyproject.toml]
    additional_dependencies: ['bandit[toml]']
    exclude: ^tests/

  # Docstring coverage
- repo: https://github.com/econchick/interrogate
  rev: 1.7.0
  hooks:
  - id: interrogate
    args: [--fail-under=50, --verbose]
    pass_filenames: false

  # Check Python docstring style
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    args: [--ignore=D100, D101, D102, D103, D104, D105, D107, D203, D213]

  # Markdown linting
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.45.0
  hooks:
  - id: markdownlint
    args: [--fix]

  # YAML formatting
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

  # Spell checker
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: [--ignore-words-list=crate, nd, sav, wel]
    exclude: ^(logs/|build/|dist/|htmlcov/)

# Configuration for ci
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
